x-environment:
  &STONEFRUIT_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
services:
  node:
    networks:
      - "stonefruit"
    build:
      context: ./data-layer/ingestors/plaid
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    volumes:
      - ./data-layer/raw:/data
    environment:
      <<: *STONEFRUIT_ENVIRONMENT
      SQLITE_DB_PATH: /data/plaid.db
  frontend:
    environment:
      - REACT_APP_API_HOST=http://node:8000
    depends_on:
      - "node"
    networks:
      - "stonefruit"
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports: ["3000:3000"]
networks:
  stonefruit:
    name: stonefruit
